version: '3.8'

# Development environment overrides for S-Entropy Framework
services:
  hugure-core:
    build:
      target: development
    environment:
      - HUGURE_ENV=development
      - RUST_LOG=hugure=debug,s_entropy=trace
      - HOT_RELOAD=true
    volumes:
      - .:/usr/src/hugure
      - cargo_cache:/usr/local/cargo/registry
      - target_cache:/usr/src/hugure/target
    command: ["cargo", "watch", "-x", "run"]
    
  hugure-entropy-solver:
    build:
      target: development
    environment:
      - RUST_LOG=entropy_solver=trace
      - DEV_MODE=true
    volumes:
      - .:/usr/src/hugure
      - cargo_cache:/usr/local/cargo/registry
    
  hugure-consciousness:
    build:
      target: development
    environment:
      - RUST_LOG=consciousness=trace
      - DEV_MODE=true
    volumes:
      - .:/usr/src/hugure
      - cargo_cache:/usr/local/cargo/registry

  # Development-only services
  adminer:
    image: adminer:latest
    container_name: hugure-adminer
    restart: unless-stopped
    ports:
      - "8090:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    networks:
      - hugure-network

volumes:
  cargo_cache:
    driver: local
  target_cache:
    driver: local 