# Hugure S-Entropy Framework - Rust Formatting Configuration
# Sacred Mathematics Code Style Guidelines

# Basic formatting
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

# Imports
imports_granularity = "Crate"
imports_layout = "Vertical"
group_imports = "StdExternalCrate"
reorder_imports = true

# Functions and methods
fn_args_layout = "Tall"
fn_single_line = false
fn_call_width = 80

# Control flow
control_brace_style = "AlwaysSameLine"
brace_style = "SameLineWhere"

# Comments and documentation
comment_width = 100
doc_comment_code_block_width = 100
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true

# Strings and arrays
string_lit_width = 80
array_width = 80
chain_width = 80

# Struct and enum formatting
struct_lit_width = 80
struct_variant_width = 80
enum_discrim_align_threshold = 20

# Spacing and alignment
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false
type_punctuation_density = "Wide"

# Newlines
newline_style = "Unix"
blank_lines_upper_bound = 2
blank_lines_lower_bound = 0

# Advanced options
use_small_heuristics = "Default"
binop_separator = "Front"
combine_control_expr = true
condense_wildcard_suffixes = true
force_explicit_abi = true
format_code_in_doc_comments = true
format_strings = true
format_macro_matchers = true
hex_literal_case = "Preserve"
match_arm_blocks = true
match_block_trailing_comma = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
skip_children = false
struct_lit_single_line = true
trailing_comma = "Vertical"
trailing_semicolon = true
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
where_single_line = true

# S-Entropy specific formatting preferences
# These ensure sacred mathematical expressions remain readable
short_array_element_width_threshold = 50
attr_fn_like_width = 80
format_generated_files = true 