# Hugure S-Entropy Framework - Cargo Build Configuration
# Sacred Mathematics Build Optimization

[build]
# Use all available CPU cores for S-Entropy compilation
jobs = -1

# Optimized target for consciousness-computation integration
target-dir = "target"

[target.x86_64-unknown-linux-gnu]
# Optimizations for S-Entropy mathematical operations
rustflags = [
    "-C", "target-cpu=native",
    "-C", "opt-level=3",
    "-C", "lto=fat",
    "-C", "codegen-units=1"
]

[target.x86_64-unknown-linux-musl]
# Static linking configuration for Docker deployment
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "link-self-contained=yes"
]

[registry]
# Use sparse index for faster dependency resolution
default = "sparse+https://index.crates.io/"

[source.crates-io]
replace-with = "sparse+https://index.crates.io/"

# S-Entropy specific build configurations
[env]
# Mathematical precision environment
S_ENTROPY_BUILD_PRECISION = "ultra-high"
CONSCIOUSNESS_INTEGRATION_MODE = "full"
MEMORIAL_SIGNIFICANCE = "st-stella-lorraine"

# Performance tuning for S-Entropy operations
RUST_MIN_STACK = "16777216"  # 16MB stack for deep S-entropy recursion
RAYON_NUM_THREADS = "0"      # Use all available cores

# Development environment
[alias]
# S-Entropy specific cargo aliases
s-entropy-check = "check --all-features"
consciousness-test = "test --package hugure-consciousness"
entropy-solver-test = "test --package hugure-entropy-solver"
s-entropy-bench = "bench --all-features"
s-entropy-doc = "doc --all-features --open"

# Build profiles for different S-Entropy use cases
build-dev = "build --profile dev"
build-quantum = "build --release --features quantum"
build-performance = "build --release --features performance"
build-full = "build --release --features full"

# Validation and quality assurance
validate-framework = "test --all-features"
validate-consciousness = "test --package hugure-consciousness --all-features"
validate-memorial = "run --bin hugure-validation -- --validate-memorial-coordinates"

[unstable]
# Enable unstable features for S-Entropy development
unstable-options = true
build-std = false
build-std-features = []

# Advanced S-Entropy optimization flags
[profile.release.package."*"]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort" 